import random

# These are lists of all the atributes the generator can choose from

mfirstname = ["Liam","Noah","Oliver","James","Elijah","Mateo","Theodore","Henry","Lucas","William","Benjamin","Sebastian","Jack","Ezra","Michael","Daniel","Leo","Samuel","Hudson","Alexander","Asher","Luca","Ethan","John","David","Jackson","Joseph","Mason","Luke","Matthew","Julian","Dylan","Elias","Jacob","Maverick","Gabriel","Logan","Aiden","Thomas","Isaac","Miles","Grayson","Santiago","Anthony","Wyatt","Carter","Jayden","Ezekie","Caleb","Cooper","Josiah","Charles","Christopher","Isaiah","Nolan","Cameron","Nathan","Joshua","Kai","Waylon","Angel","Lincoln","Andrew","Roman","Adrian","Aaron","Wesley","Ian","Axel","Brooks","Bennett","Weston","Rowan","Christian","Theo","Beau","Eli","Silas","Jonathan","Ryan","Leonardo","Walker","Jaxon","Micah","Everett","Robert","Enzo","Parker","Jeremiah","Jose","Colton","Luka","Easton","Landon","Jordan","Amir","Gael","Austin","Adam","Jameson","August","Xavier","Myles","Dominic","Damian","Nicholas","Jace","Carson","Atlas","Adriel","Kayden","Hunter","River","Greyson","Emmett","Harrison","Vincent","Milo","Jasper","Giovanni","Jonah","Zion","Connor","Sawyer","Arthur","Ryder","Archer","Lorenzo","Joel","Nathaniel"]
ffirstname = ["Olivia","Emma","Charlotte","Amelia","Sophia","Mia","Isabella","Ava","Evelyn","Luna","Harper","Sofia","Camila","Eleanor","Elizabeth","Violet","Scarlett","Emily","Hazel","Lily","Gianna","Aurora","Penelope","Aria","Nora","Chloe","Ellie","Mila","Avery","Layla","Abigail","Ella","Isla","Eliana","Nova","Madison","Zoe","Ivy","Grace","Lucy","Willow","Emilia","Riley","Naomi","Victoria","Stella","Elena","Hannah","Valentina","Maya","Zoey","Delilah","Leah","Lainey","Lillian","Paisley","Genesis","Madelyn","Sadie","Sophie","Leilani","Addison","Natalie","Josephine","Alice","Ruby","Claire","Kinsley","Everly","Emery","Adeline","Kennedy","Maeve","Audrey","Autumn","Athena","Eden","Iris","Anna","Eloise","Jade","Maria","Caroline","Brooklyn","Quinn","Aaliyah","Vivian","Liliana","Gabriella","Hailey","Sarah","Savannah","Cora","Madeline","Natalia","Ariana","Lydia","Lyla","Clara","Allison","Aubrey","Millie","Melody","Ayla","Serenity","Bella","Skylar","Sydney"]
age = [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,92,93,94,95,96,97,98,99,100]
lastnames = ["Smith","Johnson","Williams","Brown","Jones","Garcia","Miller","Davis","Rodriguez","Martinez","Hernandez","Lopez","Gonzalez","Wilson","Anderson","Thomas","Taylor","Moore","Jackson","Martin","Lee","Perez","Thompson","White","Harris","Sanchez","Clark","Ramirez","Lewis","Robinson","Walker","Young","Allen","King","Wright","Scott","Torres","Nguyen","Hill","Flores","Green","Adams","Nelson","Baker","Hall","Rivera","Campbell","Mitchell","Carter","Roberts","Gomez","Phillips","Evans","Turner","Diaz","Parker","Cruz","Edwards","Collins","Reyes","Stewart","Morris","Morales","Murphy","Cook","Rogers","Gutierrez","Ortiz","Morgan","Cooper","Peterson","Bailey","Reed","Kelly","Howard","Ramos","Kim","Cox","Ward","Richardson","Watson","Brooks","Chavez","Wood","James","Bennett","Gray","Mendoza","Ruiz","Hughes","Price","Alvarez","Castillo","Sanders","Patel","Myers","Long","Ross","Foster","Jimenez","Powell","Jenkins","Perry","Russell","Sullivan","Bell","Coleman","Butler","Henderson","Barnes","Gonzales","Fisher","Vasquez","Simmons","Romero","Jordan","Patterson","Alexander","Hamilton","Graham","Reynolds","Griffin","Wallace","Moreno","West","Cole","Hayes"]
height = [3.8,3.9,4.0,4.1,4.2,4.3,4.4,4.5,4.6,4.7,4.8,4.9,5.0,5.1,5.2,5.3,5.4,5.5,5.6,5.7,5.8,5.9,6.0,6.1,6.2,6.3,6.4,6.5,6.6]
iq = [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,92,93,94,95,96,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,123,124,125,126,127,128,129,130,131,132,133,134,135,136,137,138,139,140,141,142,143,144,145,146,147,148,149,150,151,152,153,154,155,156,157,158,159,160,161,162,163,164,165,166,167,168,169,170,171,172,173,174,175,176,177,178,179,180]
ethnicity = ["Afghan","Albanian","Algerian","American","Andorran","Angolan","Anguillan","Citizen of Antigua and Barbuda","Argentine","Armenian","Australian","Austrian","Azerbaijani","Bahamian","Bahraini","Bangladeshi","Barbadian","Belarusian","Belgian","Belizean","Beninese","Bermudian","Bhutanese","Bolivian","Citizen of Bosnia and Herzegovina","Botswanan","Brazilian","British","British Virgin Islander","Bruneian","Bulgarian","Burkinan","Burmese","Burundian","Cambodian","Cameroonian","Canadian","Cape Verdean","Cayman Islander","Central African","Chadian","Chilean","Chinese","Colombian","Comoran","Congolese","Costa Rican","Croatian","Cuban","Cymraes","Cymro","Cypriot","Czech","Danish","Djiboutian","Dominican","Citizen of the Dominican Republic","Dutch","East Timorese","Ecuadorean","Egyptian","Emirati","English","Equatorial Guinean","Eritrean","Estonian","Ethiopian","Faroese","Fijian","Filipino","Finnish","French","Gabonese","Gambian","Georgian","German","Ghanaian","Gibraltarian","Greek","Greenlandic","Grenadian","Guamanian","Guatemalan","Citizen of Guinea-Bissau","Guinean","Guyanese","Haitian","Honduran","Hong Konger","Hungarian","Icelandic","Indian","Indonesian","Iranian","Iraqi","Irish","Israeli","Italian","Ivorian","Jamaican","Japanese","Jordanian","Kazakh","Kenyan","Kittitian","Citizen of Kiribati","Kosovan","Kuwaiti","Kyrgyz","Lao","Latvian","Lebanese","Liberian","Libyan","Liechtenstein citizen","Lithuanian","Luxembourger","Macanese","Macedonian","Malagasy","Malawian","Malaysian","Maldivian","Malian","Maltese","Marshallese","Martiniquais","Mauritanian","Mauritian","Mexican","Micronesian","Moldovan","Monegasque","Mongolian","Montenegrin","Montserratian","Moroccan","Mosotho","Mozambican","Namibian","Nauruan","Nepalese","New","Zealander","Nicaraguan","Nigerien","Niuean","North Korean","Northern Irish","Norwegian","Omani","Pakistani","Palauan","Palestinian","Panamanian","Papua New Guinean","Paraguayan","Peruvian","Pitcairn Islander","Polish","Portuguese","Prydeinig","Puerto Rican","Qatari","Romanian","Russian","Rwandan","Salvadorean","Sammarinese","Samoan","Sao Tomean","Saudi Arabian","Scottish","Senegalese","Serbian","Citizen of Seychelles","Sierra Leonean","Singaporean","Slovak","Slovenian","Solomon Islander","Somali","South","African","South Korean","South Sudanese","Spanish","Sri Lankan","St Helenian","St Lucian","Stateless","Sudanese","Surinamese","Swazi","Swiss","Syrian","Taiwanese","Tajik","Tanzanian","Thai","Togolese","Tongan","Trinidadian","Tristanian","Tunisian","Turkish","Caicos Islander","Tuvaluan","Ugandan","Ukrainian","Uruguayan","Uzbek","Vatican citizen","Citizen of Vanuatu","Venezuelan","Vietnamese","Vincentian","Wallisian","Welsh","Yemeni","Zambian","Zimbabwean"]

# The "times" is how many characters you want to create

times = [10]

# The loop runs for the number you put in "times"

for n in range(times[0]):
    gender = input("Enter your gender (male or female): ",)
    
# The if statements use the user input on gender to determine the attributes it picks from    
    
    if gender == "male":
        print("Their name is ",mfirstname[random.randint(0, 129)] + " " + lastnames[random.randint(0, 126)])
        print("Their age is ",age[random.randint(0,99)]," years old")
        print("Their iq is ",iq[random.randint(0,179)])
        print("Their ethnicity is ",ethnicity[random.randint(0,221)])
        print("They are ",height[random.randint(0,28)]," feet tall\n")
    elif gender == "female":
        print("Their name is ",ffirstname[random.randint(0, 107)] + " " + lastnames[random.randint(0, 126)])
        print("Their age is ",age[random.randint(0,99)]," years old")
        print("Their iq is ",iq[random.randint(0,179)])
        print("Their ethnicity is ",ethnicity[random.randint(0,221)])
        print("They are ",height[random.randint(0,28)]," feet tall\n")
    
